2023-09-08 08:00:38 [scrapy] DEBUG: Redirecting (302) to <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM> from <GET https://www.google.com/search?q=+apple&hl=en&gl=DK&start=0>
2023-09-08 08:00:38 [scrapy] DEBUG: Redirecting (302) to <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM> from <GET https://www.google.com/search?q=+ps5&hl=en&gl=DK&start=0>
2023-09-08 08:00:39 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM> (failed 1 times): 429 Unknown Status
2023-09-08 08:00:39 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM> (failed 1 times): 429 Unknown Status
2023-09-08 08:00:39 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM> (failed 2 times): 429 Unknown Status
2023-09-08 08:00:39 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 08:00:40 [scrapy] DEBUG: Retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM> (failed 2 times): 429 Unknown Status
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 1,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-midnat/p-1803962/',
 'title': 'APPLE IPHONE 14 128 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 2,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/midnight/128-gb/1',
 'title': 'Apple iPhone 14 128GB Midnight. Min.pris: 7.202,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 3,
 'price': '7.149,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-5g-smartphone-128gb-midnight/522692',
 'title': 'iPhone 14 â€“ 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 4,
 'price': '5.761,00\xa0kr.',
 'product_url': 'https://yousee.dk/mobil/mobiltelefoner/apple/iphone-14/1468/mobil_80/kontant/',
 'title': 'Apple iPhone 14 128 GB Midnat med abonnementsaftale. Mindstepris '
          '7.075,00 kr.',
 'url': 'yousee.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 5,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Midnight/3104588?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Midnight, Mobiltelefon',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 6,
 'price': '5.706,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-14/?co=dk&utm_cluster=gradeA&utm_content=iphone-14&utm_group=iphone-14',
 'title': 'iPhone 14',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 7,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/iphone-13-128gb-green/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - GrÃ¸n med abonnementsaftale. Mindstepris '
          '6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 8,
 'price': '4.249,00\xa0kr.',
 'product_url': 'https://greenmind.dk/telefoner/iphones/iphone-12/iphone-12-pro/apple-iphone-12-pro-128-gb-stillehavsbla-brugt-okay-stand-25325',
 'title': 'Apple iPhone 12 Pro 128 GB StillehavsblÃ¥ Brugt - Okay stand',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 9,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/blue/128-gb/1',
 'title': 'Apple iPhone 14 128GB Blue.. Min.pris: 7.202,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Keyword' object has no attribute 'first'
2023-09-08 08:00:40 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+macbook&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 08:00:40 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=+iphone+13&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 1,
 'price': '28.899,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-pro-162-12cpu19gpu1tb-sg-premium-konfigureret-ud-fra-mnw93dka',
 'title': 'MacBook Pro 2023 M2 Pro 16.2" 12CPU/19GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Gave up retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM> (failed 3 times): 429 Unknown Status
2023-09-08 08:00:40 [scrapy] DEBUG: Crawled (429) <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM> (referer: None)
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 2,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-mdn',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB MDN',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 3,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgn63dka-13-256-gb-space-grey/p-1133484/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGN63DK/A 13" 256 GB SPACE GREY',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 4,
 'price': '6.084,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/macbook-pro-2019-133-tb/?co=dk&utm_cluster=gradeC&utm_content=macbook-pro-2019-133-tb&utm_group=macbook-pro-2019-133-tb',
 'title': 'Apple MacBook Pro 2019 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 5,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/computer-kontor/computere/barbar-computer/macbook-air-13-m18256-2020-space-grey/254420',
 'title': 'MacBook Air 13 M1/8/256 2020 (space grey)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 6,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-space-grey/100558134/',
 'title': 'Apple Macbook Air M1 13" 256 GB Space Grey',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 7,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/apple-macbook-air-m1-13-256-gb-guld/100558142/',
 'title': '"Apple Macbook Air M1 13 256 GB Guld"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 8,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-sg',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 9,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/apple-macbook-air-m1-13-256-gb-silver/100558137/',
 'title': '"Apple Macbook Air M1 13 256 GB Silver"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 10,
 'price': '28.899,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-max-142-12cpu30gpu1tb-sg',
 'title': 'MacBook Pro 2023 M2 Max 14.2" 12CPU/30GPU/1TB SG',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 11,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgnd3dka-13-256-gb-guld/p-1133485/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGND3DK/A 13" 256 GB GULD',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 12,
 'price': '4.425,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2017-13-3-touc/?co=dk&utm_cluster=gradeB&utm_content=apple-macbook-pro-2017-13-3-touc&utm_group=apple-macbook-pro-2017-13-3-touc',
 'title': 'Apple MacBook Pro 2017 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 13,
 'price': '5.999,00\xa0kr.',
 'product_url': 'https://prelovedelectronics.dk/products/macbook-pro-15-touch-bar-2016',
 'title': 'MacBook Pro 15" Touch Bar 2016 | i7 | 16GB | 256GB SSD - Brugt - '
          'Meget god stand | Prelovedelectronics.dk',
 'url': 'prelovedelectronics.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 14,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-guld/100558142/',
 'title': 'Apple Macbook Air M1 13" 256 GB Guld',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 15,
 'price': '10.049,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/computer-kontor/computere/barbar-computer/macbook-air-m2-2022-8256-gb-barbar-computer-midnight/474934',
 'title': 'MacBook Air M2 2022 8/256 GB bÃ¦rbar computer (Midnight)',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 16,
 'price': '4.768,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-pro-2018-13-3-touc/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-pro-2018-13-3-touc&utm_group=apple-macbook-pro-2018-13-3-touc',
 'title': 'Apple MacBook Pro 2018 | 13.3" | Touch Bar',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 17,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/apple-macbook-air-m1-13-256-gb-space-grey/100558134/',
 'title': '"Apple Macbook Air M1 13 256 GB Space Grey"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 18,
 'price': '11.299,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-pro-m2-13-3-256-gb-silver/200153771/',
 'title': 'Apple Macbook Pro M2 13,3" 256 GB Silver',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 19,
 'price': '9.999,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2022-mlxy3dka-13-256-gb-soelv/p-1535751/',
 'title': 'APPLE MACBOOK AIR 2022 MLXY3DK/A 13" 256 GB SÃ˜LV',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 20,
 'price': '1.759,00\xa0kr.',
 'product_url': 'https://greenmind.dk/computere/baerbare/apple-macbooks/apple-macbook-pro-13-3-2-7-ghz-128-gb-ssd-8-gb-early-2015-solv-danish-brugt-slidt-stand-66718',
 'title': 'Apple MacBook Pro 13.3" 2.7 GHz 8 GB 128 GB [SSD] Early 2015 SÃ¸lv '
          'Danish Brugt - Slidt stand',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 21,
 'price': '23.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-pro-2023-m2-pro-142-12cpu19gpu1tb-si',
 'title': 'MacBook Pro 2023 M2 Pro 14.2" 12CPU/19GPU/1TB SI',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 22,
 'price': '3.246,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/apple-macbook-air-2017-i-13-3/?co=dk&utm_cluster=gradeC&utm_content=apple-macbook-air-2017-i-13-3&utm_group=apple-macbook-air-2017-i-13-3',
 'title': 'Apple MacBook Air 2017 | 13.3"',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 23,
 'price': '12.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2023-m2-15-8cpu-10gpu-256gb-stl',
 'title': 'MacBook Air 2023 M2 15" 8CPU 10GPU 256GB STL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 24,
 'price': '13.199,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-10c-cpu-8gb-512gb-mdn',
 'title': 'MacBook Air 2022 M2 13.6" 10C GPU, 8GB, 512GB MDN',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 25,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.bilka.dk/produkter/apple-macbook-air-m1-13-256-gb-silver/100558137/',
 'title': 'Apple Macbook Air M1 13" 256 GB Silver',
 'url': 'bilka.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 26,
 'price': '11.499,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2023-mqkw3dka-15-256-gb-midnat/p-2279435/',
 'title': 'APPLE MACBOOK AIR 2023 MQKW3DK/A 15" 256 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 27,
 'price': '13.199,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-10c-cpu-8gb-512gb-stl',
 'title': 'MacBook Air 2022 M2 13.6" 10C GPU, 8GB, 512GB STL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 28,
 'price': '7.649,00\xa0kr.',
 'product_url': 'https://www.power.dk/computere-og-tablets/computere/baerbar-pc/apple-macbook-air-2020-m1-mgn93dka-13-256-gb-soelv/p-1133486/',
 'title': 'APPLE MACBOOK AIR 2020 M1 MGN93DK/A 13" 256 GB SÃ˜LV',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 29,
 'price': '10.499,00\xa0kr.',
 'product_url': 'https://www.humac.dk/produkter/mac/macbook-air-2022-m2-136-8c-cpu-8gb-256gb-sl',
 'title': 'MacBook Air 2022 M2 13.6" 8C GPU, 8GB, 256GB SIL',
 'url': 'humac.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' macbook',
 'position': 30,
 'price': None,
 'product_url': None,
 'title': None,
 'url': '',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 1,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-midnight/361879',
 'title': 'iPhone 13 â€“ 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 2,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/apple-iphone-13--128gb-midnight/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Midnight med abonnementsaftale. '
          'Mindstepris 6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 3,
 'price': '4.306,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13/?co=dk&utm_cluster=gradeC&utm_content=iphone-13&utm_group=iphone-13',
 'title': 'iPhone 13',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 4,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-13-128-gb-midnat/p-1204127/',
 'title': 'APPLE IPHONE 13 128 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 5,
 'price': '4.899,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-13/#/pink/128-gb/1',
 'title': 'Apple iPhone 13 128GB Pink. Min.pris: 6.702,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 6,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/iphone-13-128gb-green/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - GrÃ¸n med abonnementsaftale. Mindstepris '
          '6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 7,
 'price': '4.795,00\xa0kr.',
 'product_url': 'https://tech24.dk/products/brugt-iphone-13-128gb-som-ny-gron?variant=46819275571528&currency=DKK',
 'title': 'Brugt iPhone 13, 128GB - Som Ny - BlÃ¥ - tech24.dk Nej tak',
 'url': 'tech24.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 8,
 'price': '4.759,00\xa0kr.',
 'product_url': 'https://swappie.com/dk/iphone/iphone-13/iphone-13-128gb-bla-4/',
 'title': 'iPhone 13 128GB BlÃ¥ Apple',
 'url': 'swappie.com',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 9,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-starlight/361914',
 'title': 'iPhone 13 â€“ 5G smartphone 128GB Starlight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 10,
 'price': '4.499,00\xa0kr.',
 'product_url': 'https://greenmind.dk/telefoner/iphones/iphone-13/iphone-13-mini/apple-iphone-13-mini-128-gb-midnat-brugt-som-ny-24829',
 'title': 'Apple iPhone 13 Mini 128 GB Midnat Brugt - Som ny',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 11,
 'price': '4.680,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13/14159/?co=dk&utm_cluster=gradeA&utm_content=iphone-13-14159&utm_group=iphone-13',
 'title': 'Som Ny: iPhone 13 | 128 GB | Dual-SIM | blÃ¥',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 12,
 'price': '6.999,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-13-512-gb-stjerneskaer/p-1204138/',
 'title': 'APPLE IPHONE 13 512 GB STJERNESKÃ†R',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 13,
 'price': '6.199,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-13-5G-128GB-Midnight/2998486?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 13 5G 128GB - Midnight',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 14,
 'price': '4.306,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13/14156c/?co=dk&utm_cluster=gradeC&utm_content=iphone-13-14156c&utm_group=iphone-13',
 'title': 'iPhone 13 | 128 GB | Dual-SIM | pink',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 15,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-gron/431372',
 'title': 'iPhone 13 â€“ 5G smartphone 128GB GrÃ¸n',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 16,
 'price': '4.899,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-13/#/green/128-gb/1',
 'title': 'Apple iPhone 13 128GB Green. Min.pris: 6.702,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 17,
 'price': '4.295,00\xa0kr.',
 'product_url': 'https://tech24.dk/products/brugt-iphone-13-128gb-som-ny-pink?variant=46819277734216&currency=DKK',
 'title': 'Brugt iPhone 13, 128GB - God stand - Pink - tech24.dk Nej tak',
 'url': 'tech24.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 18,
 'price': '5.999,00\xa0kr.',
 'product_url': 'https://www.expert.dk/mobil/mobiltelefoner/apple-iphone-13-128-gb-midnat/p-1204127/',
 'title': 'APPLE IPHONE 13 128 GB MIDNAT',
 'url': 'expert.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 19,
 'price': '4.795,00\xa0kr.',
 'product_url': 'https://tech24.dk/products/brugt-iphone-13-128gb-som-ny-bla?variant=46811915092296&currency=DKK',
 'title': 'Brugt iPhone 13, 128GB - Som Ny - BlÃ¥ - tech24.dk Nej tak',
 'url': 'tech24.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 20,
 'price': '5.713,99\xa0kr.',
 'product_url': 'https://www.refurbed.dk/p/iphone-13-pro/?co=dk&utm_cluster=gradeC&utm_content=iphone-13-pro&utm_group=iphone-13-pro',
 'title': 'iPhone 13 Pro',
 'url': 'refurbed.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 21,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-13-128-gb-groen/p-1335029/',
 'title': 'APPLE IPHONE 13 128 GB GRÃ˜N',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': ' iphone 13',
 'position': 22,
 'price': None,
 'product_url': None,
 'title': None,
 'url': '',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 35, in process_item
    keyword = Keyword.objects.get(keyword=item['keyword'], domain=location.domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
search.models.Keyword.DoesNotExist: Keyword matching query does not exist.
2023-09-08 08:00:40 [scrapy] INFO: Ignoring response <429 https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bapple%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjDSlfyN9Qk15-gcxu98NO6ajeOW3i7Fq8Cb7Db5G9VwULutJf8fQan5tKfvK24ekywyAXJaAUM>: HTTP status code is not handled or not allowed
2023-09-08 08:00:40 [scrapy] ERROR: Gave up retrying <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM> (failed 3 times): 429 Unknown Status
2023-09-08 08:00:40 [scrapy] DEBUG: Crawled (429) <GET https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM> (referer: None)
2023-09-08 08:00:40 [scrapy] INFO: Ignoring response <429 https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3D%2Bps5%26hl%3Den%26gl%3DDK%26start%3D0&hl=en&q=EgRdpA0SGNec6qcGIjCzB5zT01CM07V_ADnzK68UWI6Jbj6VvswLWaM1VVbVdfScW-Q3ajMglkImnuNxTnMyAXJaAUM>: HTTP status code is not handled or not allowed
2023-09-08 08:00:40 [scrapy] INFO: Closing spider (finished)
2023-09-08 08:00:40 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 7304,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'downloader/response_bytes': 757370,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 3,
 'downloader/response_status_count/302': 2,
 'downloader/response_status_count/429': 6,
 'elapsed_time_seconds': 4.126306,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 9, 8, 3, 0, 40, 684739),
 'httpcompression/response_bytes': 2793957,
 'httpcompression/response_count': 3,
 'httperror/response_ignored_count': 2,
 'httperror/response_ignored_status_count/429': 2,
 'log_count/DEBUG': 11,
 'log_count/ERROR': 63,
 'log_count/INFO': 10,
 'response_received_count': 5,
 'retry/count': 4,
 'retry/max_reached': 2,
 'retry/reason_count/429 Unknown Status': 4,
 'scheduler/dequeued': 11,
 'scheduler/dequeued/memory': 11,
 'scheduler/enqueued': 11,
 'scheduler/enqueued/memory': 11,
 'start_time': datetime.datetime(2023, 9, 8, 3, 0, 36, 558433)}
2023-09-08 08:00:40 [scrapy] INFO: Spider closed (finished)
