2023-09-08 08:50:50 [scrapy] DEBUG: Crawled (200) <GET https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0> (referer: None)
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 1,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-midnat/p-1803962/',
 'title': 'APPLE IPHONE 14 128 GB MIDNAT',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 2,
 'price': '7.149,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-5g-smartphone-128gb-midnight/522692',
 'title': 'iPhone 14 – 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 3,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/midnight/128-gb/1',
 'title': 'Apple iPhone 14 128GB Midnight. Min.pris: 7.202,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 4,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Midnight/3104588?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Midnight, Mobiltelefon',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] DEBUG: Scraped from <200 https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0>
None
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 6,
 'price': '8.599,00\xa0kr.',
 'product_url': 'https://www.foetex.dk/produkter/iphone-14-pro-128gb-space-black/200162701/',
 'title': '"IPHONE 14 PRO 128GB SPACE BLACK"',
 'url': 'foetex.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 7,
 'price': '4.249,00\xa0kr.',
 'product_url': 'https://greenmind.dk/telefoner/iphones/iphone-12/iphone-12-pro/apple-iphone-12-pro-128-gb-stillehavsbla-brugt-okay-stand-25325',
 'title': 'Apple iPhone 12 Pro 128 GB Stillehavsblå Brugt - Okay stand',
 'url': 'greenmind.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 8,
 'price': '5.761,00\xa0kr.',
 'product_url': 'https://yousee.dk/mobil/mobiltelefoner/apple/iphone-14/1468/mobil_80/kontant/',
 'title': 'Apple iPhone 14 128 GB Midnat med abonnementsaftale. Mindstepris '
          '7.075,00 kr.',
 'url': 'yousee.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 9,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-stjerneskaer/p-1803963/',
 'title': 'APPLE IPHONE 14 128 GB STJERNESKÆR',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 10,
 'price': '5.579,00\xa0kr.',
 'product_url': 'https://swappie.com/dk/iphone/iphone-14/iphone-14-128gb-bla-18/',
 'title': 'iPhone 14 128GB Blå Apple',
 'url': 'swappie.com',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] DEBUG: Scraped from <200 https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0>
None
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 12,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Starlight/3104589?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Starlight, Mobiltelefon',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 13,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/blue/128-gb/1',
 'title': 'Apple iPhone 14 128GB Blue.. Min.pris: 7.202,00kr. 6 mdr. binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 14,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Purple. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 15,
 'price': '5.666,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-13-5g-smartphone-128gb-midnight/361879',
 'title': 'iPhone 13 – 5G smartphone 128GB Midnight',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 16,
 'price': '4.799,00\xa0kr.',
 'product_url': 'https://www.telenor.dk/shop/mobil/apple/iphone-13-128gb-green/?cycleCount=none',
 'title': 'Apple iPhone 13 - 128 GB - Grøn med abonnementsaftale. Mindstepris '
          '6613.00 Kr.',
 'url': 'telenor.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 17,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Product Red. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 18,
 'price': '6.291,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/outlet/iphone-14-5g-smartphone-128gb-product-red/653032',
 'title': 'iPhone 14 – 5G smartphone 128GB Product Red',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 19,
 'price': '5.496,00\xa0kr.',
 'product_url': 'https://www.telmore.dk/shop/mobiltelefoner/Apple/iphone-14?cid=_semt_terminal_terminal_Shopping_Shopping_u0617',
 'title': 'Apple iPhone 14 128 GB - Sky Blue. Mindstepris 7.290,00 kr.',
 'url': 'telmore.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 20,
 'price': '9.399,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-pro-5g-smartphone-128-gb-space-black/522700',
 'title': 'iPhone 14 Pro – 5G smartphone 128 GB Space Black',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 21,
 'price': '8.499,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-pro-128-gb-space-black/p-1803992/',
 'title': 'APPLE IPHONE 14 PRO 128 GB SPACE BLACK',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 22,
 'price': '7.149,00\xa0kr.',
 'product_url': 'https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-5g-smartphone-128gb-bla/522676',
 'title': 'iPhone 14 – 5G smartphone 128GB blå',
 'url': 'elgiganten.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 23,
 'price': '5.399,00\xa0kr.',
 'product_url': 'https://www.telia.dk/shop/apple/apple-iphone-14/#/starlight/128-gb/1',
 'title': 'Apple iPhone 14 128GB Starlight. Min.pris: 7.202,00kr. 6 mdr. '
          'binding',
 'url': 'telia.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 24,
 'price': '4.895,00\xa0kr.',
 'product_url': 'https://www.phonetrade.dk/kob/iphone-14/blaa-128gb-brugbar-829',
 'title': 'iPhone 14, 128GB, Blå',
 'url': 'phonetrade.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 25,
 'price': '14.683,00\xa0kr.',
 'product_url': 'https://www.boligcenter.dk/elektronik/telefoner-tablets/mobiltelefoner/smartphone-apple-iphone-14-pro-805626',
 'title': 'Smartphone Apple iPhone 14 Pro',
 'url': 'boligcenter.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] DEBUG: Scraped from <200 https://www.google.com/search?q=iphone+14&hl=en&gl=DK&start=0>
None
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 27,
 'price': '6.666,00\xa0kr.',
 'product_url': 'https://www.power.dk/mobil-og-foto/mobiltelefoner/apple-iphone-14-128-gb-blaa/p-1803966/',
 'title': 'APPLE IPHONE 14 128 GB BLÅ',
 'url': 'power.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 28,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Yellow/3151972?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Yellow, Mobiltelefon',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 29,
 'price': '6.777,00\xa0kr.',
 'product_url': 'https://www.proshop.dk/Mobil/Apple-iPhone-14-5G-128GB-Blue/3104590?utm_source=google&utm_medium=cpc&utm_campaign=searchengine',
 'title': 'Apple iPhone 14 5G 128GB - Blue, Mobiltelefon',
 'url': 'proshop.dk',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] ERROR: Error processing {'country': 'DK',
 'keyword': 'iphone 14',
 'position': 30,
 'price': None,
 'product_url': None,
 'title': None,
 'url': '',
 'user_id': 'admin'}
Traceback (most recent call last):
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Muhammad Umer\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Outputs\Django Outputs\scraper\pipelines.py", line 38, in process_item
    keyword = domain.keyword_set.filter(keyword=item['keyword'], domain=domain, user=user).first()
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keyword_set'
2023-09-08 08:50:50 [scrapy] INFO: Closing spider (finished)
2023-09-08 08:50:50 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 422,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 306527,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 3.501346,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 9, 8, 3, 50, 50, 297634),
 'httpcompression/response_bytes': 1119487,
 'httpcompression/response_count': 1,
 'item_scraped_count': 3,
 'log_count/DEBUG': 4,
 'log_count/ERROR': 27,
 'log_count/INFO': 8,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 9, 8, 3, 50, 46, 796288)}
2023-09-08 08:50:50 [scrapy] INFO: Spider closed (finished)
